# Auto-generated by .github/workflows/release-cli.yml on every cli/v* tag.
# Do not edit by hand — pushed to github.com/MedStackTS/homebrew-safenode.
class Safenode < Formula
  desc "Zero-knowledge CLI for the SafeNode credential vault"
  homepage "https://safenode.dev/cli"
  version "0.2.0"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-darwin-arm64.tar.gz"
      sha256 "309845e32be871b60e90a2c3b0a9cec6a6d36acceb0114c3198de72e53357d26"
    end
    on_intel do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-darwin-amd64.tar.gz"
      sha256 "3a687ab1f308f71771fad3a3ee5bbe1e11eee62894d050c6af1164f7291edf34"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-linux-arm64.tar.gz"
      sha256 "f50494288921f5c9d91d5f7d1a73a41f4dc6d89c4bec5164cb69f422930f94af"
    end
    on_intel do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-linux-amd64.tar.gz"
      sha256 "7e4deb164aa6fcfafc834afc0defc1a69b2069ba618976b696e15ffd82a3fdee"
    end
  end

  def install
    arch_suffix = Hardware::CPU.arm? ? "arm64" : "amd64"
    os_suffix = OS.mac? ? "darwin" : "linux"
    bin.install "safenode-#{os_suffix}-#{arch_suffix}" => "safenode"
  end

  test do
    assert_match "safenode", shell_output("#{bin}/safenode --help 2>&1", 0..2)
  end
end
