# Auto-generated by .github/workflows/release-cli.yml on every cli/v* tag.
# Do not edit by hand — pushed to github.com/MedStackTS/homebrew-safenode.
class Safenode < Formula
  desc "Zero-knowledge CLI for the SafeNode credential vault"
  homepage "https://safenode.dev/cli"
  version "0.3.0"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-darwin-arm64.tar.gz"
      sha256 "cb92980a8925d7aec645e4d53536787b0fe7f56656f814d8ce9d0b9211cf38db"
    end
    on_intel do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-darwin-amd64.tar.gz"
      sha256 "bae6c74c0c912496cb80b8b1fd498054716eb39dcb3e9743785cb91054542375"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-linux-arm64.tar.gz"
      sha256 "a2ffd72583d8c257ae08346261fab67baf11b9885fb59ecf47c9055f1a6828f5"
    end
    on_intel do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-linux-amd64.tar.gz"
      sha256 "85b49eaf69f57a1f97937c6bfe1fd5740a336b254b2f994382f6047de1048af9"
    end
  end

  def install
    arch_suffix = Hardware::CPU.arm? ? "arm64" : "amd64"
    os_suffix = OS.mac? ? "darwin" : "linux"
    bin.install "safenode-#{os_suffix}-#{arch_suffix}" => "safenode"
  end

  test do
    assert_match "safenode", shell_output("#{bin}/safenode --help 2>&1", 0..2)
  end
end
