# Auto-generated by .github/workflows/release-cli.yml on every cli/v* tag.
# Do not edit by hand — pushed to github.com/MedStackTS/homebrew-safenode.
class Safenode < Formula
  desc "Zero-knowledge CLI for the SafeNode credential vault"
  homepage "https://safenode.dev/cli"
  version "0.3.1"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-darwin-arm64.tar.gz"
      sha256 "8d27d9dde4447d9f702a121e6f9c528d0165521694124edb8db35391f7ab3cad"
    end
    on_intel do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-darwin-amd64.tar.gz"
      sha256 "2e4b70b4c0d9c86707926d9928c142d6697a97d64a426b7593a850fab72edc6c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-linux-arm64.tar.gz"
      sha256 "19a19b9f985a5f95be5ea7024fbae1c22e7d1ba9c7ea8b1adf16158d46814644"
    end
    on_intel do
      url "https://github.com/MedStackTS/homebrew-safenode/releases/download/cli/v#{version}/safenode-linux-amd64.tar.gz"
      sha256 "247597616f5673aa5e14813c7dec9560f4b83daf62792c973fcd7a2092550e8e"
    end
  end

  def install
    arch_suffix = Hardware::CPU.arm? ? "arm64" : "amd64"
    os_suffix = OS.mac? ? "darwin" : "linux"
    bin.install "safenode-#{os_suffix}-#{arch_suffix}" => "safenode"
  end

  test do
    assert_match "safenode", shell_output("#{bin}/safenode --help 2>&1", 0..2)
  end
end
